using System.Text.Json;
using HanhTrangLop1.Models;
using Microsoft.EntityFrameworkCore;

namespace HanhTrangLop1.Data;

/// <summary>Visual-first curriculum. Voice is never generated by this seed.</summary>
public static class LearningContentSeed
{
    public const string CurrentPrefix = "curriculum-v3-";
    public static readonly string[] VietnameseAlphabet = ["A","Ă","Â","B","C","D","Đ","E","Ê","G","H","I","K","L","M","N","O","Ô","Ơ","P","Q","R","S","T","U","Ư","V","X","Y"];
    public static readonly string[] EnglishAlphabet = Enumerable.Range('A', 26).Select(x => ((char)x).ToString()).ToArray();
    public static readonly string[] CombinedAlphabet = ["A","Ă","Â","B","C","D","Đ","E","Ê","F","G","H","I","J","K","L","M","N","O","Ô","Ơ","P","Q","R","S","T","U","Ư","V","W","X","Y","Z"];

    public static async Task<bool> RequiresCurriculumResetAsync(ApplicationDbContext db) =>
        await db.LearningItems.AnyAsync() && !await db.LearningItems.AnyAsync(x => x.Code.StartsWith(CurrentPrefix));

    public static async Task<(int Lessons, int Attempts, int Sessions, int Children)> ResetLearningDataAsync(ApplicationDbContext db)
    {
        await using var transaction = await db.Database.BeginTransactionAsync();
        var result = (await db.LearningItems.CountAsync(), await db.LearningAttempts.CountAsync(), await db.LearningSessions.CountAsync(), await db.ChildProfiles.CountAsync());
        await db.QuestionAttempts.ExecuteDeleteAsync(); await db.LearningAttempts.ExecuteDeleteAsync(); await db.LearningSessions.ExecuteDeleteAsync();
        await db.SkillProgress.ExecuteDeleteAsync(); await db.ChildRewards.ExecuteDeleteAsync(); await db.GardenItems.ExecuteDeleteAsync();
        await db.ChildProfiles.ExecuteDeleteAsync(); await db.ContentReviews.ExecuteDeleteAsync(); await db.Questions.ExecuteDeleteAsync();
        await db.LearningItems.ExecuteDeleteAsync(); await db.TracingTemplates.ExecuteDeleteAsync();
        await transaction.CommitAsync(); return result;
    }

    public static async Task<int> SeedAsync(ApplicationDbContext db)
    {
        var groups = await db.SkillGroups.AsNoTracking().ToDictionaryAsync(x => x.Code, StringComparer.OrdinalIgnoreCase);
        var definitions = BuildDefinitions(); ValidateDefinitions(definitions, groups.Keys);
        var existing = await db.LearningItems.Include(x => x.Questions).Where(x => x.Code.StartsWith(CurrentPrefix)).ToDictionaryAsync(x => x.Code);
        var validCodes = definitions.Select(x => x.Code).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var obsolete = existing.Values.Where(x => !validCodes.Contains(x.Code)).ToList();
        if (obsolete.Count > 0)
        {
            var ids = obsolete.Select(x => x.Id).ToArray();
            var attempted = (await db.LearningAttempts.Where(x => ids.Contains(x.LearningItemId)).Select(x => x.LearningItemId).Distinct().ToListAsync()).ToHashSet();
            db.LearningItems.RemoveRange(obsolete.Where(x => !attempted.Contains(x.Id)));
            foreach (var item in obsolete.Where(x => attempted.Contains(x.Id))) item.Status = ContentStatus.Archived;
        }
        var created = 0; var now = DateTimeOffset.UtcNow;
        foreach (var d in definitions)
        {
            if (!groups.TryGetValue(d.GroupCode, out var group)) continue;
            if (!existing.TryGetValue(d.Code, out var item)) { item = new LearningItem { Id = Guid.NewGuid(), Code = d.Code, CreatedAt = now, Questions = [] }; db.LearningItems.Add(item); created++; }
            item.Title = d.Title; item.SkillGroupId = group.Id; item.TopicId = null; item.Level = d.Level; item.SortOrder = d.SortOrder;
            item.InteractionType = d.Type; item.EstimatedMinutes = d.Type == InteractionTypes.StoryChoice ? 6 : 4; item.InstructionText = d.Instruction;
            item.ContentJson = d.PayloadJson; item.Status = ContentStatus.Published; item.PublishedAt ??= now; item.UpdatedAt = now;
            var q = item.Questions.OrderBy(x => x.SortOrder).FirstOrDefault();
            if (q is null) { q = new Question { Id = Guid.NewGuid(), LearningItemId = item.Id, SortOrder = 1 }; item.Questions.Add(q); }
            q.PromptText = d.Prompt; q.QuestionType = d.Type; q.PayloadJson = d.PayloadJson;
            q.CorrectAnswerJson = d.Type == InteractionTypes.Tracing ? JsonSerializer.Serialize(new { minPoints = 20, expectedStrokeCount = d.Strokes }) : JsonSerializer.Serialize(new { value = d.Answer });
            q.HintJson = JsonSerializer.Serialize(new { level1 = d.Hint }); q.FeedbackJson = JsonSerializer.Serialize(new { correct = "Giỏi lắm, con làm đúng rồi!", retry = "Con nhìn kỹ rồi thử lại nhé." });
            if (d.Type == InteractionTypes.Tracing)
            {
                var id = JsonSerializer.Deserialize<JsonElement>(d.PayloadJson).GetProperty("templateId").GetGuid();
                if (!await db.TracingTemplates.AnyAsync(x => x.Id == id)) db.TracingTemplates.Add(new TracingTemplate { Id = id, SymbolType = d.GroupCode == "chu-so" ? "number" : d.GroupCode == "van-dong-tinh" ? "stroke" : "letter", Symbol = d.Symbol, DisplayName = d.Title, GuideJson = JsonSerializer.Serialize(new { guideMode = "outline", expectedStrokeCount = d.Strokes, showStartPoint = true }), CreatedAt = now });
            }
        }
        await SeedReferencedImagesAsync(db, definitions);
        var removedItemIds = obsolete.Select(x => x.Id).ToArray();
        var referencedPayloads = await db.Questions
            .Where(x => x.QuestionType == InteractionTypes.Tracing && !removedItemIds.Contains(x.LearningItemId))
            .Select(x => x.PayloadJson).ToListAsync();
        referencedPayloads.AddRange(definitions.Where(x => x.Type == InteractionTypes.Tracing).Select(x => x.PayloadJson));
        var referencedTemplateIds = referencedPayloads.Select(ReadTemplateId).Where(x => x.HasValue).Select(x => x!.Value).ToHashSet();
        var orphanTemplates = await db.TracingTemplates.Where(x => !referencedTemplateIds.Contains(x.Id)).ToListAsync();
        db.TracingTemplates.RemoveRange(orphanTemplates);
        await db.SaveChangesAsync(); return created;
    }

    private static List<LessonDefinition> BuildDefinitions()
    {
        var result = new List<LessonDefinition>(); var orders = new Dictionary<string,int>();
        void Add(LessonDefinition x) { orders.TryGetValue(x.GroupCode, out var n); n += 10; orders[x.GroupCode] = n; result.Add(x with { SortOrder = n }); }
        AddAlphabet();
        void AddAlphabet()
        {
            for (var i = 0; i < CombinedAlphabet.Length; i++)
            {
                var x = CombinedAlphabet[i]; var prev = CombinedAlphabet[(i + CombinedAlphabet.Length - 1) % CombinedAlphabet.Length]; var next = CombinedAlphabet[(i + 1) % CombinedAlphabet.Length];
                var inVietnamese = VietnameseAlphabet.Contains(x); var inEnglish = EnglishAlphabet.Contains(x);
                var language = inVietnamese && inEnglish ? "Tiếng Việt và tiếng Anh" : inVietnamese ? "Tiếng Việt" : "Tiếng Anh";
                var lower = x.ToLower(new System.Globalization.CultureInfo("vi-VN"));
                var prevLower = prev.ToLower(new System.Globalization.CultureInfo("vi-VN")); var nextLower = next.ToLower(new System.Globalization.CultureInfo("vi-VN"));
                Add(Choice($"letter-combined-single-upper-{i:00}", "chu-cai", InteractionTypes.SingleChoice, $"{language}: chọn chữ hoa {x}", $"Con hãy chọn chữ hoa {x}.", [prev,x,next], x, LetterImage(x)));
                Add(Choice($"letter-combined-single-lower-{i:00}", "chu-cai", InteractionTypes.SingleChoice, $"{language}: chọn chữ thường {lower}", $"Con hãy chọn chữ thường {lower}.", [prevLower,lower,nextLower], lower));
                Add(Choice($"letter-combined-multi-{i:00}", "chu-cai", InteractionTypes.MultiSelect, $"{language}: tìm hai dạng chữ {x}", $"Chọn chữ {x} viết hoa và viết thường.", [x,lower,prev,next.ToLower(new System.Globalization.CultureInfo("vi-VN"))], Canonical([x,lower])));
                Add(Choice($"letter-combined-listen-upper-{i:00}", "chu-cai", InteractionTypes.ListenAndChoose, $"{language}: nghe và chọn chữ hoa {x}", $"Nghe và chọn chữ hoa {x}.", [next,x,prev], x));
                Add(Choice($"letter-combined-listen-lower-{i:00}", "chu-cai", InteractionTypes.ListenAndChoose, $"{language}: nghe và chọn chữ thường {lower}", $"Nghe và chọn chữ thường {lower}.", [nextLower,lower,prevLower], lower));
                Add(Tracing($"letter-combined-trace-upper-{i:00}", "chu-cai", $"{language}: tô chữ hoa {x}", x, 2));
                Add(Tracing($"letter-combined-trace-lower-{i:00}", "chu-cai", $"{language}: tô chữ thường {lower}", lower, 2));
                Add(Matching($"letter-combined-match-{i:00}", "chu-cai", $"{language}: nối chữ hoa và thường {x}", [(x,lower),(prev,prevLower),(next,nextLower)]));
            }
        }
        for (var n = 0; n <= 20; n++)
        {
            var options = NumberChoices(n);
            Add(Choice($"number-single-{n:00}", "chu-so", InteractionTypes.SingleChoice, $"Chọn số {n}", $"Con hãy chọn số {n}.", options, n.ToString(), NumberImage(n)));
            Add(Choice($"number-listen-{n:00}", "chu-so", InteractionTypes.ListenAndChoose, $"Nghe và chọn số {n}", $"Nghe và chọn số {n}.", options.Reverse().ToArray(), n.ToString()));
            Add(Tracing($"number-trace-{n:00}", "chu-so", $"Tô số {n}", n.ToString(), n > 9 ? 2 : 1));
        }
        var symbols = new[] { "🍎","⭐","🐟","🌼","🦋","🚗","🍓","🐤","🎈" };
        for (var n = 1; n <= 9; n++)
        {
            var start = Math.Min(n, 7); var nums = Enumerable.Range(start, 3).ToArray();
            Add(Matching($"number-quantity-{n}", "chu-so", $"Nối số với lượng đồ vật {n}", nums.Select(x => (x.ToString(), Repeat(symbols[n-1], x))).ToArray()));
        }
        for (var n = 1; n <= 7; n++) { var seq = Enumerable.Range(n,3).Select(x => x.ToString()).ToArray(); Add(Ordering($"number-up-{n}", "chu-so", $"Từ bé đến lớn {n}–{n+2}", "Xếp ba số từ bé đến lớn.", seq)); Add(Ordering($"number-down-{n}", "chu-so", $"Từ lớn đến bé {n+2}–{n}", "Xếp ba số từ lớn đến bé.", seq.Reverse().ToArray())); }

        var artTracingTemplates = new[]
        {
            ("phong-canh", "Phong cảnh thiên nhiên"), ("do-dung", "Đồ dùng học tập"),
            ("hinh-hoc", "Hình học kỳ diệu"), ("meo-con", "Chú mèo con"),
            ("ca-heo", "Cá heo tung tăng"), ("o-che-mua", "Chiếc ô che mưa"),
            ("trai-tao", "Quả táo và chú sâu"), ("tau-hoa", "Đoàn tàu tí hon"),
            ("chu-tho", "Chú thỏ và cà rốt"), ("ong-vang", "Ong vàng và hoa"),
            ("may-bay", "Máy bay trên trời"), ("thuyen", "Thuyền buồm lướt sóng"),
            ("cau-vong", "Cầu vồng và lâu đài"), ("chu-buom", "Bướm xinh trong vườn"),
            ("khung-long", "Khủng long tí hon"), ("ten-lua", "Tên lửa và các vì sao")
        };
        foreach (var art in artTracingTemplates)
        {
            Add(Tracing($"picture-{art.Item1}", "van-dong-tinh", $"Tô tranh: {art.Item2}", art.Item1, 6));
        }

        for (var n = 1; n <= 9; n++) { Add(Counting($"math-count-{n}", "so-luong-toan", $"Đếm {n} đồ vật", symbols[n-1], n)); Add(Quantity($"math-make-{n}", "so-luong-toan", $"Tạo đúng {n} đồ vật", symbols[n-1], n)); }
        var objects = new[] { ("🍎","quả táo"),("⭐","ngôi sao"),("🐟","con cá"),("🌼","bông hoa") };
        for (var total = 2; total <= 9; total++) { var o = objects[total % 4]; Add(Equation($"math-add-single-{total}", InteractionTypes.SingleChoice, $"Phép cộng bằng {total}", total-1, 1, "+", o.Item1, o.Item2)); Add(Equation($"math-add-drag-{total}", InteractionTypes.DragDrop, $"Kéo kết quả phép cộng {total}", total-1, 1, "+", o.Item1, o.Item2)); Add(Equation($"math-sub-single-{total}", InteractionTypes.SingleChoice, $"Phép trừ từ {total}", total, 1, "−", o.Item1, o.Item2)); Add(Equation($"math-sub-drag-{total}", InteractionTypes.DragDrop, $"Kéo kết quả phép trừ {total}", total, 1, "−", o.Item1, o.Item2)); }
        foreach (var x in new[] { (2,5,"more"),(7,3,"more"),(4,4,"equal"),(6,6,"equal"),(2,8,"less"),(5,9,"less") }) Add(Comparison($"math-compare-{x.Item3}-{x.Item1}-{x.Item2}", "so-luong-toan", $"{(x.Item3 == "equal" ? "Chọn hai nhóm bằng nhau" : x.Item3 == "less" ? "Chọn nhóm ít hơn" : "Chọn nhóm nhiều hơn")}: {x.Item1} và {x.Item2}", "●", $"Nhóm {x.Item1}", x.Item1, $"Nhóm {x.Item2}", x.Item2, x.Item3));

        AddVisualGroup("tu-duy-logic", "logic", true);
        AddVisualGroup("ky-nang-song", "life", false);
        AddVisualGroup("ngon-ngu", "language", false);
        AddVisualGroup("ghi-nho-tap-trung", "memory", true);
        AddExtraVisualLessons("tu-duy-logic", "logic"); AddExtraVisualLessons("ky-nang-song", "life"); AddExtraVisualLessons("ngon-ngu", "language"); AddExtraVisualLessons("ghi-nho-tap-trung", "memory");
        void AddVisualGroup(string group, string prefix, bool logic)
        {
            Add(Choice($"{prefix}-single-animal", group, InteractionTypes.SingleChoice, "Tìm hình phù hợp", "Vật nào là con vật?", ["Con mèo","Quả táo","Bút chì"], "Con mèo"));
            Add(Choice($"{prefix}-single-food", group, InteractionTypes.SingleChoice, "Tìm thức ăn", "Vật nào ăn được?", ["Cà rốt","Cái cốc","Quyển sách"], "Cà rốt"));
            Add(Choice($"{prefix}-multi-animals", group, InteractionTypes.MultiSelect, "Chọn các con vật", "Chọn tất cả con vật.", ["Con mèo","Con cá","Quả táo","Bút chì"], "Con cá|Con mèo"));
            Add(Choice($"{prefix}-multi-school", group, InteractionTypes.MultiSelect, "Chọn đồ dùng học tập", "Chọn tất cả đồ dùng học tập.", ["Bút chì","Quyển sách","Con thỏ","Quả cam"], "Bút chì|Quyển sách"));
            Add(Matching($"{prefix}-match-food", group, "Nối con vật với thức ăn", [("Con thỏ","Cà rốt"),("Con mèo","Con cá"),("Con ong","Bông hoa")]));
            Add(Matching($"{prefix}-match-use", group, "Nối đồ vật với công dụng", [("Cái cốc","Uống nước"),("Cái ô","Che mưa"),("Bút chì","Vẽ tranh")]));
            Add(Ordering($"{prefix}-order-morning", group, "Trình tự buổi sáng", "Xếp đúng ba bước.", ["Thức dậy","Đánh răng","Ăn sáng"]));
            Add(Ordering($"{prefix}-order-plant", group, "Cây lớn lên", "Xếp đúng ba giai đoạn.", ["Hạt giống","Mầm cây","Cây non"]));
            Add(Classification($"{prefix}-sort-food", group, "Phân loại thức ăn", ["Trái cây","Rau củ"], [("Quả táo","Trái cây"),("Quả cam","Trái cây"),("Cà rốt","Rau củ"),("Bắp cải","Rau củ")]));
            Add(Classification($"{prefix}-sort-living", group, "Phân loại hình ảnh", ["Con vật","Đồ vật"], [("Con mèo","Con vật"),("Con cá","Con vật"),("Bút chì","Đồ vật"),("Cái cốc","Đồ vật")]));
            if (group == "ngon-ngu" || group == "ghi-nho-tap-trung") { Add(Choice($"{prefix}-listen-cat", group, InteractionTypes.ListenAndChoose, "Nghe từ con mèo", "Nghe và chọn con mèo.", ["Con chó","Con mèo","Con vịt"], "Con mèo")); Add(Choice($"{prefix}-listen-apple", group, InteractionTypes.ListenAndChoose, "Nghe từ quả táo", "Nghe và chọn quả táo.", ["Quả táo","Quả cam","Cà rốt"], "Quả táo")); }
            if (!logic) AddStories(group, group == "ky-nang-song" ? Stories.Take(6) : Stories.Skip(6));
        }
        void AddExtraVisualLessons(string group, string prefix)
        {
            Add(Choice($"{prefix}-single-weather", group, InteractionTypes.SingleChoice, "Chọn hình theo thời tiết", "Trời mưa cần vật nào?", ["Cái ô","Kính râm","Quạt giấy"], "Cái ô"));
            Add(Choice($"{prefix}-single-action", group, InteractionTypes.SingleChoice, "Chọn hành động phù hợp", "Muốn vẽ tranh con chọn gì?", ["Bút chì","Cái thìa","Đôi dép"], "Bút chì"));
            Add(Choice($"{prefix}-single-home", group, InteractionTypes.SingleChoice, "Tìm nơi ở phù hợp", "Con cá sống ở đâu?", ["Dưới nước","Trên cây","Trong cặp"], "Dưới nước"));
            Add(Choice($"{prefix}-multi-fruit", group, InteractionTypes.MultiSelect, "Chọn các loại quả", "Chọn tất cả các loại quả.", ["Quả táo","Quả cam","Cà rốt","Bút chì"], "Quả cam|Quả táo"));
            Add(Choice($"{prefix}-multi-safe", group, InteractionTypes.MultiSelect, "Chọn việc an toàn", "Chọn các việc an toàn.", ["Nắm tay người lớn","Cài dây an toàn","Chạm ổ điện","Chơi gần bếp nóng"], "Cài dây an toàn|Nắm tay người lớn"));
            Add(Choice($"{prefix}-multi-water", group, InteractionTypes.MultiSelect, "Chọn con vật dưới nước", "Chọn các con vật sống dưới nước.", ["Con cá","Con tôm","Con mèo","Con thỏ"], "Con cá|Con tôm"));
            Add(Matching($"{prefix}-match-home", group, "Nối con vật với nơi sống", [("Con cá","Dưới nước"),("Con chim","Tổ chim"),("Con chó","Ngôi nhà")]));
            Add(Matching($"{prefix}-match-weather", group, "Nối thời tiết với đồ dùng", [("Trời mưa","Cái ô"),("Trời nắng","Mũ rộng vành"),("Trời lạnh","Áo ấm")]));
            Add(Matching($"{prefix}-match-shape", group, "Nối đồ vật với hình dạng", [("Quả bóng","Hình tròn"),("Cái hộp","Hình vuông"),("Mái nhà","Hình tam giác")]));
            Add(Ordering($"{prefix}-order-hands", group, "Ba bước rửa tay", "Xếp đúng ba bước.", ["Làm ướt tay","Xoa xà phòng","Rửa sạch"]));
            Add(Ordering($"{prefix}-order-story", group, "Trình tự câu chuyện ngắn", "Xếp việc xảy ra trước đến sau.", ["Gieo hạt","Tưới nước","Cây nảy mầm"]));
            Add(Ordering($"{prefix}-order-school", group, "Ba bước vào lớp", "Xếp đúng ba bước.", ["Chào cô","Cất ba lô","Ngồi vào chỗ"]));
            Add(Classification($"{prefix}-sort-habitat", group, "Phân loại nơi sống", ["Trên cạn","Dưới nước"], [("Con mèo","Trên cạn"),("Con thỏ","Trên cạn"),("Con cá","Dưới nước"),("Con tôm","Dưới nước")]));
            Add(Classification($"{prefix}-sort-weather", group, "Phân loại đồ dùng thời tiết", ["Ngày mưa","Ngày nắng"], [("Cái ô","Ngày mưa"),("Áo mưa","Ngày mưa"),("Kính râm","Ngày nắng"),("Mũ rộng vành","Ngày nắng")]));
            Add(Classification($"{prefix}-sort-shape", group, "Phân loại hình", ["Có góc","Không có góc"], [("Hình vuông","Có góc"),("Hình tam giác","Có góc"),("Hình tròn","Không có góc"),("Hình bầu dục","Không có góc")]));
        }

        foreach (var shape in new[] { ("circle","Hình tròn"),("square","Hình vuông"),("triangle","Hình tam giác"),("rectangle","Hình chữ nhật") }) Add(Choice($"shape-single-{shape.Item1}", "hinh-dang-khong-gian", InteractionTypes.SingleChoice, $"Nhận biết {shape.Item2}", $"Đâu là {shape.Item2}?", ["Hình tròn","Hình vuông","Hình tam giác","Hình chữ nhật"], shape.Item2));
        Add(Matching("shape-match", "hinh-dang-khong-gian", "Nối hình với tên", [("●","Hình tròn"),("■","Hình vuông"),("▲","Hình tam giác")]));
        Add(Matching("shape-match-object", "hinh-dang-khong-gian", "Nối đồ vật với hình dạng", [("Quả bóng","Hình tròn"),("Cái hộp","Hình vuông"),("Mái nhà","Hình tam giác")]));
        Add(Matching("shape-match-same", "hinh-dang-khong-gian", "Nối hai hình giống nhau", [("Tròn đỏ","Hình tròn"),("Vuông xanh","Hình vuông"),("Tam giác vàng","Hình tam giác")]));
        Add(Classification("shape-sort-corners", "hinh-dang-khong-gian", "Phân loại theo góc", ["Có góc","Không có góc"], [("Hình vuông","Có góc"),("Hình tam giác","Có góc"),("Hình tròn","Không có góc"),("Hình bầu dục","Không có góc")]));
        Add(Classification("shape-sort-round", "hinh-dang-khong-gian", "Phân loại hình tròn", ["Dạng tròn","Không tròn"], [("Hình tròn","Dạng tròn"),("Hình bầu dục","Dạng tròn"),("Hình vuông","Không tròn"),("Hình tam giác","Không tròn")]));
        Add(Classification("shape-sort-size", "hinh-dang-khong-gian", "Phân loại kích thước", ["Hình lớn","Hình nhỏ"], [("Tròn lớn","Hình lớn"),("Vuông lớn","Hình lớn"),("Tròn nhỏ","Hình nhỏ"),("Vuông nhỏ","Hình nhỏ")]));
        Add(Choice("shape-drag-above", "hinh-dang-khong-gian", InteractionTypes.DragDrop, "Vị trí phía trên", "Kéo quả bóng vào phía trên.", ["Quả bóng","Quyển sách","Cái cốc"], "Quả bóng"));
        Add(Choice("shape-drag-inside", "hinh-dang-khong-gian", InteractionTypes.DragDrop, "Vị trí bên trong", "Kéo con mèo vào trong ngôi nhà.", ["Con mèo","Con cá","Con chim"], "Con mèo"));
        Add(Choice("shape-drag-below", "hinh-dang-khong-gian", InteractionTypes.DragDrop, "Vị trí phía dưới", "Kéo quả bóng vào phía dưới.", ["Quả bóng","Cái ô","Bông hoa"], "Quả bóng"));
        foreach (var x in new[] { ("circle","●","Hình tròn"),("square","■","Hình vuông"),("triangle","▲","Hình tam giác") }) { Add(ShapeComparison($"shape-{x.Item1}-large", $"Chọn {x.Item3} lớn hơn", x.Item2, x.Item3, 132, 72, "more")); Add(ShapeComparison($"shape-{x.Item1}-small", $"Chọn {x.Item3} nhỏ hơn", x.Item2, x.Item3, 80, 138, "less")); }

        var basicWritingStrokes = new[]
        {
            ("vertical", "Nét sổ thẳng", "nét sổ thẳng"),
            ("horizontal", "Nét ngang", "nét ngang"),
            ("diagonal-left", "Nét xiên trái", "nét xiên trái"),
            ("diagonal-right", "Nét xiên phải", "nét xiên phải"),
            ("hook-forward", "Nét móc xuôi", "nét móc xuôi"),
            ("hook-reverse", "Nét móc ngược", "nét móc ngược"),
            ("double-hook", "Nét móc hai đầu", "nét móc hai đầu"),
            ("open-curve-right", "Nét cong hở phải", "nét cong hở phải"),
            ("open-curve-left", "Nét cong hở trái", "nét cong hở trái"),
            ("closed-curve", "Nét cong kín", "nét cong kín"),
            ("upper-loop", "Nét khuyết trên", "nét khuyết trên"),
            ("lower-loop", "Nét khuyết dưới", "nét khuyết dưới"),
            ("knot", "Nét thắt", "nét thắt")
        };
        foreach (var stroke in basicWritingStrokes)
        {
            Add(Tracing($"motor-{stroke.Item1}", "van-dong-tinh", $"Tô {stroke.Item2.ToLowerInvariant()}", stroke.Item3, 1));
        }
        Add(Ordering("motor-order-paper", "van-dong-tinh", "Gấp giấy ba bước", "Xếp đúng thứ tự.", ["Đặt giấy","Gấp đôi","Miết nếp"])); Add(Ordering("motor-order-color", "van-dong-tinh", "Tô màu gọn gàng", "Xếp đúng thứ tự.", ["Chọn màu","Tô trong viền","Cất bút"]));
        Add(Choice("motor-drag-rabbit", "van-dong-tinh", InteractionTypes.DragDrop, "Đưa thỏ tới cà rốt", "Kéo con thỏ tới cà rốt.", ["Con thỏ","Con mèo","Con cá"], "Con thỏ")); Add(Choice("motor-drag-bee", "van-dong-tinh", InteractionTypes.DragDrop, "Đưa ong tới hoa", "Kéo con ong tới bông hoa.", ["Con ong","Con cá","Con chó"], "Con ong"));
        Add(Matching("motor-match-tools", "van-dong-tinh", "Nối dụng cụ với hoạt động", [("Bút chì","Vẽ nét"),("Bút màu","Tô màu"),("Giấy","Gấp hình")])); Add(Matching("motor-match-craft", "van-dong-tinh", "Nối đồ thủ công", [("Kéo","Cắt giấy"),("Hồ dán","Dán hình"),("Đất nặn","Nặn bóng")])); Add(Matching("motor-match-line", "van-dong-tinh", "Nối nét với hình", [("Nét tròn","Quả bóng"),("Nét thẳng","Cái bút"),("Nét cong","Cầu vồng")]));
        Add(Choice("motor-single-color", "van-dong-tinh", InteractionTypes.SingleChoice, "Chọn dụng cụ tô", "Dụng cụ nào dùng để tô màu?", ["Bút màu","Cái thìa","Đôi dép"], "Bút màu")); Add(Choice("motor-single-cut", "van-dong-tinh", InteractionTypes.SingleChoice, "Chọn dụng cụ cắt giấy", "Dụng cụ nào dùng để cắt giấy?", ["Kéo","Bút chì","Cái cốc"], "Kéo")); Add(Choice("motor-single-fold", "van-dong-tinh", InteractionTypes.SingleChoice, "Chọn vật để gấp", "Vật nào dùng để gấp hình?", ["Giấy màu","Quả táo","Cái thìa"], "Giấy màu"));
        Add(Choice("motor-multi-craft", "van-dong-tinh", InteractionTypes.MultiSelect, "Đồ làm thủ công", "Chọn đồ dùng làm thủ công.", ["Giấy màu","Hồ dán","Cái cốc","Quả táo"], "Giấy màu|Hồ dán")); Add(Choice("motor-multi-draw", "van-dong-tinh", InteractionTypes.MultiSelect, "Đồ dùng để vẽ", "Chọn các đồ dùng để vẽ.", ["Bút chì","Bút màu","Đôi dép","Cái bát"], "Bút chì|Bút màu")); Add(Choice("motor-multi-model", "van-dong-tinh", InteractionTypes.MultiSelect, "Đồ dùng để tạo hình", "Chọn các đồ dùng để tạo hình.", ["Đất nặn","Giấy màu","Cái ô","Quả cam"], "Giấy màu|Đất nặn"));

        Add(Classification("world-habitat", "kham-pha", "Con vật sống ở đâu", ["Trên cạn","Dưới nước"], [("Con mèo","Trên cạn"),("Con chó","Trên cạn"),("Con cá","Dưới nước"),("Con tôm","Dưới nước")])); Add(Classification("world-plants", "kham-pha", "Phân loại cây", ["Cây cho quả","Cây cho hoa"], [("Cây táo","Cây cho quả"),("Cây cam","Cây cho quả"),("Hoa hồng","Cây cho hoa"),("Hoa cúc","Cây cho hoa")]));
        foreach (var x in new[] { ("cat","meo meo","Con mèo"),("dog","gâu gâu","Con chó"),("duck","cạp cạp","Con vịt") }) Add(Choice($"world-listen-{x.Item1}", "kham-pha", InteractionTypes.ListenAndChoose, $"Nghe tiếng {x.Item2}", $"Con gì kêu {x.Item2}?", [x.Item3,"Con cá","Con ong"], x.Item3));
        Add(Matching("world-food", "kham-pha", "Nối con vật với thức ăn", [("Con thỏ","Cà rốt"),("Con mèo","Con cá"),("Con ong","Bông hoa")])); Add(Matching("world-weather", "kham-pha", "Nối thời tiết với đồ dùng", [("Trời mưa","Cái ô"),("Trời nắng","Mũ rộng vành"),("Trời lạnh","Áo ấm")]));
        Add(Choice("world-single-rain", "kham-pha", InteractionTypes.SingleChoice, "Đồ dùng ngày mưa", "Trời mưa cần vật nào?", ["Cái ô","Kính râm","Quạt giấy"], "Cái ô")); Add(Choice("world-single-plant", "kham-pha", InteractionTypes.SingleChoice, "Cây cần gì", "Cây cần gì để lớn?", ["Nước","Đồ chơi","Bút chì"], "Nước")); Add(Choice("world-multi-fly", "kham-pha", InteractionTypes.MultiSelect, "Con vật biết bay", "Chọn các con vật biết bay.", ["Con chim","Con bướm","Con cá","Con mèo"], "Con bướm|Con chim")); Add(Ordering("world-order-plant", "kham-pha", "Hạt thành cây", "Xếp quá trình cây lớn lên.", ["Hạt giống","Mầm cây","Cây non"]));
        Add(Choice("world-single-animal", "kham-pha", InteractionTypes.SingleChoice, "Con vật dưới nước", "Con nào sống dưới nước?", ["Con cá","Con mèo","Con thỏ"], "Con cá")); Add(Choice("world-single-sun", "kham-pha", InteractionTypes.SingleChoice, "Bầu trời ban ngày", "Ban ngày con thường thấy gì?", ["Mặt trời","Mặt trăng","Ngôi sao"], "Mặt trời"));
        Add(Choice("world-multi-fruit", "kham-pha", InteractionTypes.MultiSelect, "Cây cho quả", "Chọn các loại quả.", ["Quả táo","Quả cam","Bông hoa","Bút chì"], "Quả cam|Quả táo")); Add(Choice("world-multi-water", "kham-pha", InteractionTypes.MultiSelect, "Chọn nhiều con vật dưới nước", "Chọn các con vật dưới nước.", ["Con cá","Con tôm","Con chó","Con chim"], "Con cá|Con tôm"));
        Add(Ordering("world-order-day", "kham-pha", "Các buổi trong ngày", "Xếp đúng thứ tự.", ["Buổi sáng","Buổi trưa","Buổi tối"])); Add(Ordering("world-order-butterfly", "kham-pha", "Bướm lớn lên", "Xếp đúng quá trình.", ["Trứng","Sâu non","Bướm"]));
        Add(Story("world-story-seed", "kham-pha", "Hạt mầm lớn lên", "Bé gieo hạt vào đất và tưới nước mỗi ngày. Ít hôm sau, một mầm xanh nhú lên.", "Bé làm gì mỗi ngày?", ["Tưới nước","Cất hạt","Không chăm sóc"], "Tưới nước", "/images/pictograms/seedling.svg"));
        EnsureExtendedCoverage();
        return result;

        void AddStories(string group, IEnumerable<StorySpec> stories) { foreach (var s in stories) Add(Story($"{group}-story-{s.Slug}", group, s.Title, s.Speech, s.Prompt, s.Choices, s.Answer, $"/images/lessons/doc-hieu/ill-{s.Slug}.jpg")); }
        void EnsureExtendedCoverage()
        {
            var extendedGroups = new[] { "tu-duy-logic", "ky-nang-song", "ngon-ngu", "hinh-dang-khong-gian", "ghi-nho-tap-trung", "van-dong-tinh", "kham-pha" };
            foreach (var group in extendedGroups)
            {
                var profile = CoverageProfiles[group];
                var rule = ActivityTemplateCatalog.ForSkillGroup(group);
                var types = rule.InteractionTypes.Concat(rule.AllowsTracing ? [InteractionTypes.Tracing] : []);
                foreach (var type in types)
                {
                    var current = result.Count(x => x.GroupCode == group && x.Type == type);
                    for (var index = current; index < 16; index++) Add(CreateCoverageLesson(profile, type, index));
                }
            }
        }
    }

    private static LessonDefinition CreateCoverageLesson(CoverageProfile profile, string type, int index)
    {
        string Item(int offset) => profile.Items[(index + offset) % profile.Items.Length];
        (string Left, string Right) Pair(int offset) => profile.Pairs[(index + offset) % profile.Pairs.Length];
        var typeName = ActivityTemplateCatalog.GetDisplayName(type);
        var slug = $"coverage-{profile.Code}-{type}-{index:00}";
        var title = $"{typeName}: {profile.Theme} {index + 1:00}";
        return type switch
        {
            InteractionTypes.SingleChoice => Choice(slug, profile.GroupCode, type, title, $"Con hãy chọn {Item(0)}.", [Item(1),Item(0),Item(2)], Item(0)),
            InteractionTypes.ListenAndChoose => Choice(slug, profile.GroupCode, type, title, $"Nghe và chọn {Item(0)}.", [Item(2),Item(0),Item(1)], Item(0)),
            InteractionTypes.DragDrop => Choice(slug, profile.GroupCode, type, title, $"Kéo {Pair(0).Left} tới {Pair(0).Right}.", [Pair(0).Left,Item(1),Item(2)], Pair(0).Left, "", new { targetLabel=Pair(0).Right }),
            InteractionTypes.MultiSelect => Choice(slug, profile.GroupCode, type, title, $"Chọn {Item(0)} và {Item(1)}.", [Item(0),Item(2),Item(1),Item(3)], Canonical([Item(0),Item(1)])),
            InteractionTypes.Matching => Matching(slug, profile.GroupCode, title, [Pair(0),Pair(1),Pair(2)]),
            InteractionTypes.Ordering => Ordering(slug, profile.GroupCode, title, "Quan sát mẫu rồi xếp lại ba hình theo đúng thứ tự.", [Item(0),Item(1),Item(2)]),
            InteractionTypes.Classification => Classification(slug, profile.GroupCode, title, [profile.CategoryA,profile.CategoryB],
                [(profile.CategoryAItems[index%profile.CategoryAItems.Length],profile.CategoryA),(profile.CategoryAItems[(index+1)%profile.CategoryAItems.Length],profile.CategoryA),(profile.CategoryBItems[index%profile.CategoryBItems.Length],profile.CategoryB),(profile.CategoryBItems[(index+1)%profile.CategoryBItems.Length],profile.CategoryB)]),
            InteractionTypes.StoryChoice => Story(slug, profile.GroupCode, title,
                $"Trong câu chuyện nhỏ, bạn An nhìn thấy {Pair(0).Left}. An nhớ rằng {Pair(0).Left} đi cùng với {Pair(0).Right}. An quan sát thật kỹ rồi vui vẻ hoàn thành hoạt động.",
                $"An nhìn thấy gì?", [Pair(0).Left,Item(1),Item(2)], Pair(0).Left, ImageForLabel(Pair(0).Left)),
            InteractionTypes.Comparison => ShapeComparison(slug, title, new[]{"●","■","▲"}[index%3], new[]{"Hình tròn","Hình vuông","Hình tam giác"}[index%3], 62+(index%4)*18, 126-(index%3)*12, index%2==0?"more":"less"),
            InteractionTypes.Tracing => Tracing(slug, profile.GroupCode, title, new[]{"|","—","/","\\","C","S","O","U","∩","∪","Z","M","W","△","□","○"}[index%16], 1),
            _ => throw new InvalidOperationException($"Không thể tạo bài phủ cho dạng {type}.")
        };
    }

    private static LessonDefinition Choice(string slug, string group, string type, string title, string prompt, string[] choices, string answer, string image = "", object? extra = null) => New(slug, group, type, title, type == InteractionTypes.ListenAndChoose ? "Con nghe rồi chọn một đáp án." : type == InteractionTypes.MultiSelect ? "Con chọn tất cả đáp án đúng." : type == InteractionTypes.DragDrop ? "Con kéo đáp án vào vùng đích." : "Con nhìn hình rồi chọn một đáp án.", prompt, Merge(new { choices, targetLabel = type == InteractionTypes.DragDrop ? "Kết quả" : "", imageUrl = image, imageAltText = title, questionAudioUrl = "", questionAudioUrlEn = "", optionAudio = new { }, optionAudioEn = new { } }, extra), answer);
    private static LessonDefinition Equation(string slug, string type, string title, int left, int right, string op, string symbol, string name) { var answer = op == "+" ? left+right : left-right; return Choice(slug, "so-luong-toan", type, title, $"Có {left} {name}, {(op == "+" ? "thêm" : "bớt")} {right}. Có bao nhiêu?", [Math.Max(0,answer-1).ToString(),answer.ToString(),(answer+1).ToString()], answer.ToString(), "", new { visualMode = "equation", equation = new { leftCount = left, rightCount = right, @operator = op, objectSymbol = symbol } }); }
    private static LessonDefinition Matching(string slug, string group, string title, (string Left,string Right)[] pairs) => New(slug, group, InteractionTypes.Matching, title, "Con nối từng cặp phù hợp.", title, new { pairs = pairs.Select(x => new { left=x.Left,right=x.Right }), imageUrl="" }, CanonicalMappings(pairs));
    private static LessonDefinition Ordering(string slug, string group, string title, string prompt, string[] items) => New(slug, group, InteractionTypes.Ordering, title, "Con dùng mũi tên để sắp xếp.", prompt, new { items, imageUrl="" }, string.Join('|',items));
    private static LessonDefinition Classification(string slug, string group, string title, string[] categories, (string Item,string Category)[] mappings) => New(slug, group, InteractionTypes.Classification, title, "Con đưa từng hình vào đúng nhóm.", title, new { categories, mappings=mappings.Select(x => new { left=x.Item,right=x.Category }), imageUrl="" }, CanonicalMappings(mappings));
    private static LessonDefinition Counting(string slug, string group, string title, string symbol, int count) => New(slug, group, InteractionTypes.Counting, title, "Chạm từng đồ vật để đếm rồi chọn số.", "Có bao nhiêu đồ vật?", new { choices=NumberChoices(count), objectSymbol=symbol,targetCount=count,imageUrl="",visualMode="symbols-only" }, count.ToString());
    private static LessonDefinition Quantity(string slug, string group, string title, string symbol, int count) => New(slug, group, InteractionTypes.QuantityBuilder, title, "Thêm hoặc bớt để tạo đúng số lượng.", $"Hãy tạo {count} đồ vật.", new { objectSymbol=symbol,targetCount=count,maxItems=Math.Min(12,count+3),targetLabel=$"Mục tiêu: {count}",imageUrl="" }, count.ToString());
    private static LessonDefinition Comparison(string slug,string group,string title,string symbol,string leftLabel,int leftCount,string rightLabel,int rightCount,string mode) => New(slug,group,InteractionTypes.Comparison,title,"Quan sát rồi chọn nhóm phù hợp.",title,new { visualMode="quantity",objectSymbol=symbol,leftLabel,leftCount,rightLabel,rightCount,comparisonMode=mode,imageUrl="" }, mode=="equal"?"equal":mode=="less"?(leftCount<rightCount?"left":"right"):(leftCount>rightCount?"left":"right"));
    private static LessonDefinition ShapeComparison(string slug,string title,string symbol,string shape,int left,int right,string mode) => New(slug,"hinh-dang-khong-gian",InteractionTypes.Comparison,title,"Nhìn kích thước rồi chọn hình phù hợp.",title,new { visualMode="shape",objectSymbol=symbol,shapeName=shape,leftLabel="Bên trái",rightLabel="Bên phải",leftCount=left,rightCount=right,comparisonMode=mode,imageUrl="" }, mode=="less"?(left<right?"left":"right"):(left>right?"left":"right"));
    private static LessonDefinition Story(string slug,string group,string title,string speech,string prompt,string[] choices,string answer,string image,IReadOnlyDictionary<string,string>? media=null) => New(slug,group,InteractionTypes.StoryChoice,title,"Xem tranh, nghe truyện rồi trả lời.",prompt,new { choices,speechText=speech,audioUrl="",audioUrlEn="",imageUrl=image,imageAltText=title,itemMedia=media??new Dictionary<string,string>() },answer);
    private static LessonDefinition Tracing(string slug,string group,string title,string symbol,int strokes) { var id=StableGuid(CurrentPrefix+slug); return New(slug,group,InteractionTypes.Tracing,title,"Tô theo đường nét gợi ý.",$"Con hãy tô {symbol} theo đường viền.",new { symbol,templateId=id,guideMode="outline",expectedStrokeCount=strokes,showStartPoint=true,audioUrl="",imageUrl="" },symbol,symbol,strokes); }
    private static LessonDefinition New(string slug,string group,string type,string title,string instruction,string prompt,object payload,string answer,string symbol="",int strokes=1) => new(CurrentPrefix+slug,group,type,title,instruction,prompt,JsonSerializer.Serialize(payload),answer,"Con nhìn kỹ hình và nghe lại yêu cầu nhé.",symbol,strokes);
    private static object Merge(object basis, object? extra) { var o=JsonSerializer.SerializeToNode(basis)!.AsObject(); if(extra is not null) foreach(var p in JsonSerializer.SerializeToNode(extra)!.AsObject()) o[p.Key]=p.Value?.DeepClone(); return o; }
    private static string[] NumberChoices(int n) => new[]{Math.Max(0,n-1).ToString(),n.ToString(),Math.Min(20,n+1).ToString()}.Distinct().ToArray();
    private static string Repeat(string x,int n)=>string.Join(' ',Enumerable.Repeat(x,n)); private static string Canonical(IEnumerable<string> x)=>string.Join('|',x.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(v=>v,StringComparer.OrdinalIgnoreCase)); private static string CanonicalMappings(IEnumerable<(string Left,string Right)> x)=>string.Join('|',x.OrderBy(v=>v.Left,StringComparer.OrdinalIgnoreCase).Select(v=>$"{v.Left}=>{v.Right}"));
    private static string LetterImage(string x) { var lower=x.ToLower(new System.Globalization.CultureInfo("vi-VN")); return $"/images/photos/flashcard-letter-{lower}.{("ăâđêôơư".Contains(lower)?"svg":"jpg")}"; } private static string NumberImage(int n)=>n==0?"/images/photos/flashcard-number-0.svg":$"/images/photos/flashcard-number-{n}.jpg";
    public static string ResolveLetterFlashcardUrl(string symbol)=>LegacyLearningContentSeed.ResolveLetterFlashcardUrl(symbol); public static string ResolveTracingFlashcardUrl(string symbol)=>LegacyLearningContentSeed.ResolveTracingFlashcardUrl(symbol); private static Guid StableGuid(string value)=>new(System.Security.Cryptography.MD5.HashData(System.Text.Encoding.UTF8.GetBytes(value)));

    private static void ValidateDefinitions(IReadOnlyCollection<LessonDefinition> ds,IEnumerable<string> groups)
    {
        var duplicateCodes=ds.GroupBy(x=>x.Code).Where(x=>x.Count()>1).Select(x=>x.Key).ToArray(); var duplicateTitles=ds.GroupBy(x=>$"{x.GroupCode}|{x.Title}",StringComparer.OrdinalIgnoreCase).Where(x=>x.Count()>1).Select(x=>x.Key).ToArray();
        if(duplicateCodes.Length>0||duplicateTitles.Length>0) throw new InvalidOperationException($"Kho bài học có mã hoặc tên bị lặp. Mã: {string.Join(",",duplicateCodes)}; tên: {string.Join(",",duplicateTitles)}");
        foreach(var group in groups) { var list=ds.Where(x=>x.GroupCode.Equals(group,StringComparison.OrdinalIgnoreCase)).ToList(); if(list.Count<5) throw new InvalidOperationException($"Nhóm {group} chưa đủ bài."); var rule=ActivityTemplateCatalog.ForSkillGroup(group); var missing=rule.InteractionTypes.Concat(rule.AllowsTracing?[InteractionTypes.Tracing]:[]).Where(t=>list.All(x=>x.Type!=t)); if(missing.Any()) throw new InvalidOperationException($"Nhóm {group} thiếu dạng: {string.Join(", ",missing)}"); }
        var extendedGroups=new[]{"tu-duy-logic","ky-nang-song","ngon-ngu","hinh-dang-khong-gian","ghi-nho-tap-trung","van-dong-tinh","kham-pha"};
        foreach(var group in extendedGroups) { var rule=ActivityTemplateCatalog.ForSkillGroup(group); foreach(var type in rule.InteractionTypes.Concat(rule.AllowsTracing?[InteractionTypes.Tracing]:[])) { var count=ds.Count(x=>x.GroupCode==group&&x.Type==type); if(count<16) throw new InvalidOperationException($"Nhóm {group}, dạng {type} chỉ có {count} bài; yêu cầu tối thiểu 16 bài."); } }
        var expected=CombinedAlphabet.Length;
        foreach(var type in new[]{InteractionTypes.MultiSelect,InteractionTypes.Matching}) if(ds.Count(x=>x.GroupCode=="chu-cai"&&x.Type==type)!=expected) throw new InvalidOperationException($"Dạng {type} phải đủ {expected} bài chữ đã gộp Việt–Anh.");
        foreach(var type in new[]{InteractionTypes.SingleChoice,InteractionTypes.ListenAndChoose,InteractionTypes.Tracing}) if(ds.Count(x=>x.GroupCode=="chu-cai"&&x.Type==type)!=expected*2) throw new InvalidOperationException($"Dạng {type} phải đủ {expected} chữ hoa và {expected} chữ thường.");
        if(ds.Count(x=>x.GroupCode=="van-dong-tinh"&&x.Type==InteractionTypes.Tracing&&x.Code.Contains("picture-",StringComparison.OrdinalIgnoreCase))<16) throw new InvalidOperationException("Tô tranh & Tạo hình nghệ thuật phải có ít nhất 16 tranh.");
    }
    private static async Task SeedReferencedImagesAsync(ApplicationDbContext db,IEnumerable<LessonDefinition> ds)
    {
        var paths=ds.SelectMany(x=>ExtractImagePaths(x.PayloadJson)).Distinct(StringComparer.OrdinalIgnoreCase).ToList(); var existing=(await db.MediaAssets.Where(x=>x.AssetType=="image").Select(x=>x.StoragePath).ToListAsync()).ToHashSet(StringComparer.OrdinalIgnoreCase);
        foreach(var path in paths.Where(x=>!existing.Contains(x))) db.MediaAssets.Add(new MediaAsset{Id=Guid.NewGuid(),AssetType="image",FileName=Path.GetFileName(path),ContentType=Path.GetExtension(path).Equals(".svg",StringComparison.OrdinalIgnoreCase)?"image/svg+xml":"image/jpeg",StoragePath=path,AltText="Hình minh họa bài học",CreatedAt=DateTimeOffset.UtcNow});
    }
    private static IEnumerable<string> ExtractImagePaths(string json) { using var doc=JsonDocument.Parse(json); return Walk(doc.RootElement).ToArray(); static IEnumerable<string> Walk(JsonElement e) { if(e.ValueKind==JsonValueKind.Object) foreach(var p in e.EnumerateObject()) foreach(var x in Walk(p.Value)) yield return x; else if(e.ValueKind==JsonValueKind.Array) foreach(var c in e.EnumerateArray()) foreach(var x in Walk(c)) yield return x; else if(e.ValueKind==JsonValueKind.String&&e.GetString() is {Length:>0} s&&s.StartsWith("/images/")) yield return s; } }
    private static Guid? ReadTemplateId(string json) { try { using var doc=JsonDocument.Parse(json); return doc.RootElement.TryGetProperty("templateId",out var value)&&value.TryGetGuid(out var id)?id:null; } catch(JsonException) { return null; } }
    private sealed record LessonDefinition(string Code,string GroupCode,string Type,string Title,string Instruction,string Prompt,string PayloadJson,string Answer,string Hint,string Symbol="",int Strokes=1,byte Level=1,int SortOrder=0);
    private sealed record StorySpec(string Slug,string Title,string Speech,string Prompt,string[] Choices,string Answer);
    private sealed record CoverageProfile(string Code,string GroupCode,string Theme,string[] Items,(string Left,string Right)[] Pairs,string CategoryA,string CategoryB,string[] CategoryAItems,string[] CategoryBItems);
    private static string ImageForLabel(string label)
    {
        var value=label.ToLowerInvariant();
        var file=value.Contains("mèo")?"cat":value.Contains("chó")?"dog":value.Contains("tôm")?"shrimp":value.Contains("cá")?"fish":value.Contains("thỏ")?"rabbit":value.Contains("chim")?"bird":value.Contains("ong")?"bee":value.Contains("táo")?"apple":value.Contains("cam")?"orange":value.Contains("cà rốt")?"carrot":value.Contains("hoa")?"flower":value.Contains("bút")?"pencil":value.Contains("sách")?"book":value.Contains("cặp")?"backpack":value.Contains("cốc")?"bowl":value.Contains("xà phòng")||value.Contains("rửa tay")?"soap":value.Contains("bàn chải")||value.Contains("đánh răng")?"toothbrush":value.Contains("xin lỗi")?"folded-hands":value.Contains("cảm ơn")||value.Contains("nắm tay")?"handshake":value.Contains("dây an toàn")?"car":value.Contains("giày")?"shoe":value.Contains("áo mưa")?"coat":value.Contains("ô")?"umbrella":value.Contains("mũ")?"helmet":value.Contains("mặt trăng")||value.Contains("ban đêm")?"moon":value.Contains("mặt trời")||value.Contains("trời nắng")?"sun":value.Contains("trời mưa")||value.Contains("nước")?"water":value.Contains("cây")||value.Contains("hạt")?"seedling":value.Contains("bóng")?"ball":value.Contains("xe")?"car":"book";
        return $"/images/pictograms/{file}.svg";
    }
    private static readonly IReadOnlyDictionary<string,CoverageProfile> CoverageProfiles = new Dictionary<string,CoverageProfile>
    {
        ["tu-duy-logic"]=new("logic","tu-duy-logic","tư duy bằng hình",["Con mèo","Con cá","Con thỏ","Quả táo","Quả cam","Cà rốt","Bút chì","Quyển sách","Quả bóng","Cái ô","Bông hoa","Xe đạp","Con chó","Con vịt","Con ong","Cái cốc","Cái thìa","Cặp sách"],[("Con thỏ","Cà rốt"),("Con mèo","Con cá"),("Con ong","Bông hoa"),("Bút chì","Quyển sách"),("Cái ô","Trời mưa"),("Xe đạp","Gara"),("Cái cốc","Uống nước"),("Quả bóng","Hình tròn"),("Con cá","Dưới nước"),("Con chim","Tổ chim"),("Quả táo","Trái cây"),("Cà rốt","Rau củ"),("Con chó","Ngôi nhà"),("Cặp sách","Đi học"),("Cái thìa","Cái bát"),("Quả cam","Trái cây")],"Con vật","Đồ vật",["Con mèo","Con cá","Con thỏ","Con chó","Con vịt","Con ong"],["Bút chì","Quyển sách","Quả bóng","Cái ô","Cái cốc","Cái thìa"]),
        ["ky-nang-song"]=new("life","ky-nang-song","kỹ năng an toàn",["Rửa tay","Đánh răng","Đội mũ bảo hiểm","Nắm tay người lớn","Cài dây an toàn","Cảm ơn","Xin lỗi","Cái ô","Áo mưa","Bàn chải","Xà phòng","Cặp sách","Quyển sách","Bút chì","Áo ấm","Mũ rộng vành","Cái cốc","Đôi giày"],[("Xà phòng","Rửa tay"),("Bàn chải","Đánh răng"),("Mũ bảo hiểm","Đi xe an toàn"),("Cái ô","Che mưa"),("Áo ấm","Trời lạnh"),("Cặp sách","Đi học"),("Bút chì","Vẽ tranh"),("Cái cốc","Uống nước"),("Nắm tay người lớn","Qua đường"),("Cài dây an toàn","Ngồi ô tô"),("Cảm ơn","Được giúp đỡ"),("Xin lỗi","Làm bạn buồn"),("Đôi giày","Đi ra ngoài"),("Áo mưa","Trời mưa"),("Quyển sách","Đọc sách"),("Mũ rộng vành","Trời nắng")],"An toàn","Cần tránh",["Nắm tay người lớn","Cài dây an toàn","Đội mũ bảo hiểm","Rửa tay","Đánh răng","Đi cùng người lớn"],["Chạm ổ điện","Chơi gần bếp nóng","Chạy qua đường","Đùa trên xe","Vứt rác bừa bãi","Chơi với dao"]),
        ["ngon-ngu"]=new("language","ngon-ngu","ngôn ngữ qua tranh",["Con mèo","Con cá","Con thỏ","Con chó","Con chim","Quả táo","Quả cam","Cà rốt","Bút chì","Quyển sách","Cái cốc","Cái ô","Quả bóng","Bông hoa","Xe đạp","Cặp sách","Mặt trời","Mặt trăng"],[("Mèo","Con mèo"),("Cá","Con cá"),("Thỏ","Con thỏ"),("Chó","Con chó"),("Chim","Con chim"),("Táo","Quả táo"),("Cam","Quả cam"),("Bút","Bút chì"),("Sách","Quyển sách"),("Cốc","Cái cốc"),("Ô","Cái ô"),("Bóng","Quả bóng"),("Hoa","Bông hoa"),("Xe","Xe đạp"),("Cặp","Cặp sách"),("Trăng","Mặt trăng")],"Con vật","Đồ vật",["Con mèo","Con cá","Con thỏ","Con chó","Con chim","Con ong"],["Bút chì","Quyển sách","Cái cốc","Cái ô","Quả bóng","Cặp sách"]),
        ["hinh-dang-khong-gian"]=new("shape","hinh-dang-khong-gian","hình dạng và vị trí",["Hình tròn","Hình vuông","Hình tam giác","Hình chữ nhật","Hình bầu dục","Quả bóng","Cái hộp","Mái nhà","Cái đĩa","Quyển sách","Cái cửa","Bông hoa","Ngôi sao","Mặt trời","Cái cốc","Cái ô","Bên trên","Bên dưới"],[("Quả bóng","Hình tròn"),("Cái hộp","Hình vuông"),("Mái nhà","Hình tam giác"),("Quyển sách","Hình chữ nhật"),("Cái đĩa","Hình tròn"),("Cái cửa","Hình chữ nhật"),("Mặt trời","Hình tròn"),("Ngôi sao","Hình ngôi sao"),("Bông hoa","Dạng tròn"),("Cái cốc","Hình trụ"),("Cái ô","Dạng cong"),("Hình bầu dục","Không có góc"),("Hình vuông","Bốn góc"),("Hình tam giác","Ba góc"),("Bên trên","Vị trí cao"),("Bên dưới","Vị trí thấp")],"Có góc","Không có góc",["Hình vuông","Hình tam giác","Hình chữ nhật","Cái hộp","Mái nhà","Quyển sách"],["Hình tròn","Hình bầu dục","Quả bóng","Cái đĩa","Mặt trời","Bông hoa"]),
        ["ghi-nho-tap-trung"]=new("memory","ghi-nho-tap-trung","ghi nhớ hình ảnh",["Quả táo đỏ","Quả cam vàng","Con mèo","Con cá","Bút chì","Quyển sách","Quả bóng","Cái ô","Con thỏ","Bông hoa","Xe đạp","Cặp sách","Con chó","Con vịt","Mặt trời","Mặt trăng","Cái cốc","Cà rốt"],[("Quả táo đỏ","Quả táo đỏ"),("Con mèo","Con mèo"),("Con cá","Con cá"),("Bút chì","Bút chì"),("Quyển sách","Quyển sách"),("Quả bóng","Quả bóng"),("Cái ô","Cái ô"),("Con thỏ","Con thỏ"),("Bông hoa","Bông hoa"),("Xe đạp","Xe đạp"),("Cặp sách","Cặp sách"),("Con chó","Con chó"),("Con vịt","Con vịt"),("Mặt trời","Mặt trời"),("Cái cốc","Cái cốc"),("Cà rốt","Cà rốt")],"Con vật","Đồ vật",["Con mèo","Con cá","Con thỏ","Con chó","Con vịt","Con ong"],["Bút chì","Quyển sách","Quả bóng","Cái ô","Cái cốc","Cặp sách"]),
        ["van-dong-tinh"]=new("motor","van-dong-tinh","khéo tay",["Bút chì","Bút màu","Kéo","Giấy màu","Hồ dán","Đất nặn","Nét thẳng","Nét cong","Vòng tròn","Quả bóng","Bông hoa","Cái cốc","Quyển sách","Cặp sách","Con thỏ","Con ong","Cà rốt","Bàn chải"],[("Bút chì","Vẽ nét"),("Bút màu","Tô màu"),("Kéo","Cắt giấy"),("Hồ dán","Dán hình"),("Đất nặn","Nặn bóng"),("Giấy màu","Gấp hình"),("Nét tròn","Quả bóng"),("Nét cong","Cầu vồng"),("Nét thẳng","Bút chì"),("Con thỏ","Cà rốt"),("Con ong","Bông hoa"),("Bàn chải","Đánh răng"),("Quyển sách","Lật trang"),("Cặp sách","Cài khóa"),("Cái cốc","Cầm chắc"),("Bông hoa","Tô màu")],"Dụng cụ","Sản phẩm",["Bút chì","Bút màu","Kéo","Giấy màu","Hồ dán","Đất nặn"],["Tranh vẽ","Hình cắt","Hình dán","Quả bóng nặn","Thuyền giấy","Bông hoa giấy"]),
        ["kham-pha"]=new("world","kham-pha","khám phá thế giới",["Con mèo","Con chó","Con cá","Con tôm","Con chim","Con ong","Con thỏ","Bông hoa","Cây táo","Hạt giống","Mặt trời","Mặt trăng","Cái ô","Áo mưa","Xe đạp","Ô tô","Quả táo","Cà rốt"],[("Con thỏ","Cà rốt"),("Con mèo","Con cá"),("Con ong","Bông hoa"),("Con cá","Dưới nước"),("Con chim","Tổ chim"),("Con chó","Ngôi nhà"),("Hạt giống","Mầm cây"),("Cây táo","Quả táo"),("Trời mưa","Cái ô"),("Trời nắng","Mặt trời"),("Ban đêm","Mặt trăng"),("Xe đạp","Đường bộ"),("Ô tô","Đường bộ"),("Con tôm","Dưới nước"),("Bông hoa","Con ong"),("Cà rốt","Rau củ")],"Trên cạn","Dưới nước",["Con mèo","Con chó","Con thỏ","Con chim","Con ong","Gà con"],["Con cá","Con tôm","Cá heo","Cua","Bạch tuộc","Rùa biển"])
    };
    private static readonly StorySpec[] Stories =
    [
        new("gau-mat-ong","Chú gấu và mật ong","Gấu nâu thấy tổ ong trong rừng. Gấu chỉ lấy một ít mật ong và để lại cho các bạn ong.","Gấu lấy bao nhiêu mật ong?",["Một ít","Lấy hết","Không lấy"],"Một ít"),
        new("cao-chiec-khan","Cáo nhỏ và chiếc khăn","Cáo nhặt chiếc khăn xanh. Khi biết khăn của sóc nâu, cáo trả lại ngay.","Cáo làm gì?",["Trả lại khăn","Giấu khăn","Bỏ chạy"],"Trả lại khăn"),
        new("chiec-o-vang","Chiếc ô màu vàng","Trời mưa, Na dùng chiếc ô vàng che cho chú mèo nhỏ.","Na giúp con vật nào?",["Con mèo","Con cá","Con thỏ"],"Con mèo"),
        new("chim-non-tap-bay","Chim non tập bay","Chim non chưa bay xa. Mẹ động viên chim luyện tập mỗi ngày.","Chim cần làm gì?",["Luyện tập","Bỏ cuộc","Nằm ngủ"],"Luyện tập"),
        new("rua-dong-suoi","Rùa nhỏ và dòng suối","Thỏ trắng làm chiếc bè giúp rùa nhỏ qua dòng suối an toàn.","Ai giúp rùa?",["Thỏ trắng","Sóc nâu","Gà con"],"Thỏ trắng"),
        new("chiec-hop-bi-mat","Chiếc hộp bí mật","Sinh nhật, Bin nhận hộp quà từ mẹ. Trong hộp là quyển sách tranh.","Trong hộp có gì?",["Quyển sách","Quả bóng","Cái ô"],"Quyển sách"),
        new("soc-hat-de","Chú sóc và hạt dẻ","Mùa thu, sóc chăm chỉ nhặt hạt dẻ để dành cho mùa đông.","Sóc nhặt gì?",["Hạt dẻ","Quả táo","Bông hoa"],"Hạt dẻ"),
        new("nhim-qua-tao","Chú nhím và quả táo","Nhím kiên trì lăn quả táo to về hang.","Nhím làm gì với táo?",["Lăn về hang","Ném đi","Bỏ lại"],"Lăn về hang"),
        new("tho-cu-ca-rot","Chú thỏ và củ cà rốt","Thỏ trắng kéo mạnh và nhổ được củ cà rốt lớn.","Thỏ tìm thấy gì?",["Củ cà rốt","Quả táo","Quyển sách"],"Củ cà rốt"),
        new("chiec-thuyen-giay","Chiếc thuyền giấy","An gấp thuyền giấy và thả xuống vũng nước sau mưa.","An gấp gì?",["Thuyền giấy","Máy bay giấy","Cái mũ"],"Thuyền giấy"),
        new("tho-con-ca-rot","Thỏ con chăm vườn","Thỏ nhổ cỏ và tưới nước. Cà rốt lớn lên thật ngọt.","Thỏ tưới gì?",["Vườn cà rốt","Cái bàn","Đồ chơi"],"Vườn cà rốt")
    ];
}
